apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: pd
    app.kubernetes.io/instance: baseline-cluster
    app.kubernetes.io/managed-by: tikv-operator
    app.kubernetes.io/name: tikv-cluster
  name: baseline-cluster-pd-lb
  namespace: default
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app.kubernetes.io/component: pd
    app.kubernetes.io/instance: baseline-cluster
    app.kubernetes.io/managed-by: tikv-operator
    app.kubernetes.io/name: tikv-cluster
  type: LoadBalancer